<?xml version="1.0" encoding="UTF-8" ?>
<testsuites errors="0"
            failures="1"
            tests="5">

  <testsuite name="Employeemsnsger"
    errors="0" failures="1" hostname="" id="" package="Employeemsnsger" skipped="0"
    tests="5" time="13.88" timestamp="">
  
    <testcase name="Problem 1" classname="Employeemsnsger" time="6.041" assertions="2">

    

    
    </testcase>
  
    <testcase name="Problem 2" classname="Employeemsnsger" time="1.274" assertions="3">

    

    

    
    </testcase>
  
    <testcase name="Problem 3" classname="Employeemsnsger" time="1.084" assertions="3">

    

    

    
    </testcase>
  
    <testcase name="Problem 4" classname="Employeemsnsger" time="0.2420" assertions="0">
    </testcase>
  
    <testcase name="Problem 5" classname="Employeemsnsger" time="5.237" assertions="1">  <failure message="Timed out while waiting for element &lt;[name=&#34;employee4&#34;]&gt; to be present for 5000 milliseconds. - expected [0;32m&#34;visible&#34;[0m but got: [0;31m&#34;not found&#34;[0m">    at Object.Problem 5 (/Users/Josephstone/DevMountain/practiceAutomation/tests/Employeemsnsger.js:55:14)
    at process._tickCallback (internal/process/next_tick.js:68:7)</failure>

    <failure message="    at Object.Problem 5 (/Users/Josephstone/DevMountain/practiceAutomation/tests/Employeemsnsger.js:55:14)">    at process._tickCallback (internal/process/next_tick.js:68:7)</failure>
    </testcase>
  

  

  
  </testsuite>
</testsuites>
